[versions]
adventure = "[4,5)"
slf4j = "[2,3)"

[libraries]
annotations = "org.jetbrains:annotations:26.0.2-1"
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
gson = "com.google.code.gson:gson:2.13.2"
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-bom = "org.junit:junit-bom:6.0.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.35.0"
shadow = "com.gradleup.shadow:9.3.0"
